[tool.poetry]
name = "ajc27-freemocap-blender-addon"
version = "0.1.0"
description = "A add-on to import FreeMoCap data into Blender (based on @ajc27's addon)"
authors = ["Skelly FreeMoCap <info@freemocap.org>"]
license = "AGPLv3"
readme = "README.md"
packages = [{include = "ajc27_freemocap_blender_addon"}]

[tool.poetry.dependencies]
python = ">3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
